# ============================================================
# HouseGarden - Configuracion Spring Boot
# Aprendices: Laura Combita - Diana Amaya | Ficha: 3118327
# ============================================================

server.port=8080
server.servlet.context-path=/housegarden-spring

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/housegarden?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
